### ISSUE TITLE
Error in visualization and download

### ISSUE THREAD

**Issue by arnoweiss** [eclipse-tractusx/sldt-semantic-hub#157]
[In this deployment](https://portal.int.demo.catena-x.net/semantichub/urn%3Abamm%3Aio.catenax.week_based_capacity_group%3A1.0.0%23WeekBasedCapacityGroup), there is an error when inspecting the WeekBasedCapacityGroup. Downloads return html instead of the desired artifacts and the frontend doesn't render the pages properly. Since neither function, I suspect this is a backend issue with the semantic hub and not due to the portal's visualization. Screenshot:

![image](https://github.com/eclipse-tractusx/sldt-semantic-hub/assets/86715435/f5d501ab-b38b-4ebe-b305-6777e10feba8)

A failed download for the aspect-ttl looks like this:

```html
<!doctype html><html lang="en"><head><meta charset="utf-8"/><link rel="icon" href="data:image/x-icon;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAYAAABXAvmHAAAAAXNSR0IArs4c6QAABT1JREFUaEPlWT1MY0cQ/ubZkEhJ4TRJS9oIg9FhpFSBpDgp8SNcF0xxRkkPaS8Fpri0QJ8I7iTs64AzKZNAFQkjYWyU9qBMmoCUSLnEZqJ9frbfz+6+fTa6QLKlPW9nvtnZ+WZmCQMu3kQKr2EFQAGECZrH+YBbxvqcYkkHhLmMaTA2AYw4fxFmaB4Hg+wZ99u+AXAJawCWfQrvAgA3ZH4EkAl5604AKGELwEPpUd8RAC+6MR9EcUcAsPKi/R8B7PyUGUkmmw+JaITZzWbAJZgOmi1r78H7NW1ajpWFeBsZEE5u4gSE4UNDrRVmFCJS567FrdVPpn6uyeSMAXAZK2AUtcoMQmjnJJNKNFsrFEzBUQTAtGxP1TfC1y7iQy5jxCWr6SgdILyrY+Lvjt7LsJXY8YRK5JZeASJs5SYbi77fdDvwNpZAjtdTBpquKK+Wq1RHVwDSn6CBEhBv2JNnXQKVhpBDVq9jDdHx2VPJWKQFhyN8S3j9mpKbAIeJz8RgqQzP2Nkzp2QJAdAyrVzhlSjkKI/d4N+Vo7ElEK/3baf6wwM725gJAejD+EMQCsG4b6fGlijyou9Nz8hDAjlOYPAcgA90wIeH6Z374/VffSfAJQhvLRl4THi9SHlH3rdcr5veGzBwRYSCPdnwnWDlKL0FUpQsQqNFs/a9eqULwC2NRZEWtU5BmAt5/SSTSjYdrwvvGS0C9v5OJgoPJmqXsg8qx+kaGOOy/wg0n8vWn3kB7ILxqVYzY5UWwlxQOU7PuanWJFs5XrdAxVy2rr0flePRdTDJI8LlBQcAP8UbSOL3CONDWUaQUlyvAzhsNhOFYIng8I3IKp6OrlIdKwIsur3QYvDXs9mzr9oASvgQwPcaABuU9zcvleroNBFtmpKSzutccsJOhF+K8r3MaA7gGT7DNcpKAC/xFi2iG6fPq+m1WKUA4dS6bhWC9Yyb9Xz3pj8AZXwOxjdSAIQ9mu9dzP3q2DKDRTtpuGjVztZDDOz1unej/gBs4zEIj6QWBS5upTp2YsSqeq+LuPb3067yVwAgrW5oOh4g3mgmksVgegxNMSQe+5cB0AVwXejUKV77pFOMWwWA8aQ5lFgOeb3dBImLalLMnVK+J2eehWLdAX8IqUoBJz2bNEG+Y/IT5X41vcuQkyuBvshl69+2eaBPAKpSwG2Cdgy93oHg4xqXJH9TpTpfKREXgPA6GMuzU41Q/R+zCRL2SctxbRkBIGHRRx/fq/8Q+wREg/JXa/hSWgq056TmJTRhD3+i4CVJgej5UbpA7XujXMPD9Ob98fofHQCPQHiskA6VEUE5FSlp9A/UBInQzWUbTtXbBqAvJWqUx4TMGFkpYEDPN9AEBVpKLsEWJ6dRvk55fBnI690CzMDoTqwP3gTJmnp+ireRxC8RhogmunNpxTDKPNaBG2qC6KKZtDJeruk1NCXnYULbhxp62i92Q00QCKfNRGI6SJReACIkRO6+qXUqxjK0gNBI0CTLeI3QtZ7Bpl49+48DS+H1zhb7x+kXJo2QSesZngsNFkoX7phF+U7mjlzEG4N+Kcrx4Efyydw2iiDn5THO2sBLFIOkFNxAtKIARUw/5E2QzBjldNoZpVsoRk4qAGleVyGPAmBxa0I1So8FoCPsFmZzIOdJVYxNUiCc4xo1WDiI+6waBcDONoxH/l0mjhMng8r+xwHQhZ2ttx/NDVes4zLcUyumPQHGE3uqEfXk5Nv/9gBQMG2U024HgECBFmV0gKXjiA8u6w8h9RTDVNMrPwH3lfKciLdksyNTwzty/wATsrFPLbsvywAAAABJRU5ErkJggg=="><meta name="viewport" content="width=device-width,initial-scale=1"/><link rel="manifest" href="/manifest.json"/><title></title><script defer="defer" src="/static/js/main.7c721c40.js"></script><link href="/static/css/main.a00cac5d.css" rel="stylesheet"></head><body><div id="app"></div><script>const ENV={PORTAL_ASSETS_URL:"https://portal.int.demo.catena-x.net/assets",PORTAL_BACKEND_URL:"https://portal-backend.int.demo.catena-x.net",CENTRALIDP_URL:"https://centralidp.int.demo.catena-x.net/auth",BPDM_API_URL:"https://business-partners.int.demo.catena-x.net/api",SEMANTICS_URL:"https://semantics.int.demo.catena-x.net",MANAGED_IDENTITY_WALLETS_NEW_URL:"https://managed-identity-wallets-new.int.demo.catena-x.net"}</script></body></html>

```

**Comment by richaashara** [comment]
@arnoweiss and @thomas-henn,

This issue in the Semantic Hub is specifically regarding image generation for models using the SDK. Which is already fixed in the Semantic Hub 0.2.15 version.

The error occurred during the generation of SVG or PNG images for models, as the SDK was creating new temporary files for each "get diagram" request. This process would eventually lead to memory saturation and subsequently, the pod will go down.

For the older version of the BAMM model, we were utilizing the Open Manufacturing SDK, while the BAMM 2.1 and SAMM models relied on the ESMF SDK for diagram generation.

I am pleased to inform you that I have successfully addressed and resolved this issue for the ESMF SDK. The corresponding pull request has already been merged in SDK version 2.2.3.

In our discussions with Roman and Matthias, we determined that we had not pursued a fix for the Open Manufacturing SDK, as we were aware of its impending removal from the Semantic Hub. Consequently, in the latest Semantic Hub version, the usage of Open Manufacturing SDK has been eliminated.

Please be advised that this image generation issue will persist only for older BAMM models, as the Open Manufacturing SDK is used. if we use SH version 0.2.14 or lower. We anticipated that this problem would persist until the older SDK is removed from the codebase.

If you have any further questions or concerns, please don't hesitate to reach out if not then I request to close this issue.

**Comment by tunacicek** [comment]
@richaashara , @ma3u , @arnoweiss : The backend is updated to the newest sdk (2.4.2). 
Is the UI Part done?

**Comment by richaashara** [comment]
@tunacicek , Could you please check from portal team for the UI issue.

**Comment by ds-lcapellino** [comment]
We could possibly look into the problem of the UI. For this we would need the following information:
 
- How does the backend need to be called (url) to get a diagram back to a semantic model?
- How must the backend be called (url) to get back a semantic model file (.json, .ttl , ... )?
 
We may also need support to run the test scenario locally. Although it should be easy to start the frontend locally, the question remains whether we can easily access the test scenario in the local development environment.

**Comment by RazvanZmau** [comment]
Fixed
