### ISSUE TITLE
Sprint recurring task- Check ESMF SDK new release version and update the same in Semantic-hub & semantic-models (generate.sh)

### ISSUE THREAD

**Issue by RazvanZmau** [eclipse-tractusx/sldt-semantic-hub#212]
Sprint recurring task- Check ESMF SDK new release version and update the same in Semantic-hub & semantic-models (generate.sh)

Update SAMM SDK version in semantic-models - generate.sh - https://github.com/eclipse-tractusx/sldt-semantic-models/blob/main/generate.sh

**Comment by agg3fe** [comment]
New emsf-sdk 2.5.0 version has been released. https://github.com/eclipse-esmf/esmf-sdk/releases/tag/v2.5.0

**Comment by agg3fe** [comment]
Latest esmf sdk 2.5.1 has been updated in [semantic models ](https://github.com/eclipse-tractusx/sldt-semantic-models/blob/main/generate.sh)
Work left is to update sdk in semantic hub.

**Comment by agg3fe** [comment]
The new esmf sdk 2.5.1 is creating problem in semantic-hub. The download is aasx file is failing. Hence not updating the dependency in semantic-hub for now and closing this ticket.
First of all, with current samm sdk 2.4.2, there is some problem with upload of models in semantic-hub. The validation is failing for various valid models. That should be resolved first. This issue is addressed in ticket #237
