### ISSUE TITLE
Support migration of Catena-X BAMM models to the SAMM meta model

### ISSUE THREAD

**Issue by RazvanZmau** [eclipse-tractusx/sldt-semantic-hub#215]
Take a look inside ticket https://jira.catena-x.net/browse/A1SLDT-1152

**Comment by agg3fe** [comment]
Updates awaited for Bamm models left: https://confluence.catena-x.net/display/CORE/CTSM+2024-02-05-Focus+SAMM

**Comment by agg3fe** [comment]
All models are converted from Bamm to Samm.
The status for converted models are kept as 'Draft' and not 'Released'. So that we can still use these models for any kind of updates in future and then change the status to 'release'. 
example: https://github.com/eclipse-tractusx/sldt-semantic-models/blob/main/io.catenax.eol_story/2.0.0/metadata.json
